source "https://rubygems.org"
gem "jekyll", "~> 4.3.2"
gem "minimal-mistakes-jekyll"
gem "jekyll-feed"
gem "jemoji"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-redirect-from"
gem "jekyll-include-cache"